In [36]:
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
data = pd.read_csv('data/Iris.csv')
data_training = data[0:int(len(data)*3/5)]
data_test = data[int(len(data)*3/5):len(data)]
#分割
train_x = np.array(data_training.iloc[:, [i for i in range(data_training.shape[1]-1)]])
train_y = np.array(data_training['Species'])
test_x = np.array(data_test.iloc[:, [i for i in range(data_test.shape[1]-1)]])
test_y = np.array(data_test['Species'])
print("load data")

load data


In [37]:
clf=XGBClassifier(base_score=0.5, booster='gbtree', learning_rate=0.05, max_depth=8, n_estimators=50)
clf.fit(train_x, train_y)

[16:31:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


D:\software\Anoconda\envs\env_lime\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.05, max_delta_step=0, max_depth=8,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=50, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [38]:
print(clf.score(test_x, test_y))

1.0


D:\software\Anoconda\envs\env_lime\lib\site-packages\xgboost\data.py:115: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "memory consumption")


In [47]:
print(test_x)

[[121.    6.9   3.2   5.7   2.3]
 [122.    5.6   2.8   4.9   2. ]
 [123.    7.7   2.8   6.7   2. ]
 [124.    6.3   2.7   4.9   1.8]
 [125.    6.7   3.3   5.7   2.1]
 [126.    7.2   3.2   6.    1.8]
 [127.    6.2   2.8   4.8   1.8]
 [128.    6.1   3.    4.9   1.8]
 [129.    6.4   2.8   5.6   2.1]
 [130.    7.2   3.    5.8   1.6]
 [131.    7.4   2.8   6.1   1.9]
 [132.    7.9   3.8   6.4   2. ]
 [133.    6.4   2.8   5.6   2.2]
 [134.    6.3   2.8   5.1   1.5]
 [135.    6.1   2.6   5.6   1.4]
 [136.    7.7   3.    6.1   2.3]
 [137.    6.3   3.4   5.6   2.4]
 [138.    6.4   3.1   5.5   1.8]
 [139.    6.    3.    4.8   1.8]
 [140.    6.9   3.1   5.4   2.1]
 [141.    6.7   3.1   5.6   2.4]
 [142.    6.9   3.1   5.1   2.3]
 [143.    5.8   2.7   5.1   1.9]
 [144.    6.8   3.2   5.9   2.3]
 [145.    6.7   3.3   5.7   2.5]
 [146.    6.7   3.    5.2   2.3]
 [147.    6.3   2.5   5.    1.9]
 [148.    6.5   3.    5.2   2. ]
 [149.    6.2   3.4   5.4   2.3]
 [150.    5.9   3.    5.1   1.8]]
